version: '3.3'

services:
  db:
    image: postgres:latest
    container_name: postgres
    hostname: db-postgres

    volumes:
      - db-postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test

    ports:
      - 127.0.0.1:4040:5432

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-app
    depends_on:
      - postgres
    ports:
      - "8181:8181"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres-db
      SPRING_DATASOURCE_USERNAME: your_username
      SPRING_DATASOURCE_PASSWORD: your_password
    volumes:
      - ./db/changelog:/db/changelog

volumes:
  db-postgres-data:
