version: '3.8'

services:
  postgres-db:
    image: postgres:latest
    container_name: postgres-db
    hostname: db-postgres
    volumes:
      - db-postgres-data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: postgres-db
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test
    ports:
      - '4141:5432'
    command: -p 4141

  my-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my-fintech-app
    depends_on:
      - postgres-db
    ports:
      - '8282:8181'
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:4141/postgres-db
      SPRING_DATASOURCE_USERNAME: test
      SPRING_DATASOURCE_PASSWORD: test
    volumes:
      - ./db/changelog:/db/changelog


volumes:
  db-postgres-data:
