spring:
  application:
    name: fintech
  datasource:
    url: jdbc:postgresql://localhost:4040/postgres-db
    password: test
    username: test
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
server:
  port: 8181

mybatis:
  configuration:
    map-underscore-to-camel-case: true
    default-statement-timeout: 3000
    use-generated-keys: true